"""Initial migration.

Revision ID: ce40d0628a86
Revises: 
Create Date: 2024-07-24 15:31:50.790252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce40d0628a86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('estimate_time', sa.String(length=80), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testcases')
    # ### end Alembic commands ###
